Add an option to force writing to stdout
robenkleene/rep-grep pull request #37
Opened 2023-12-30 18:34 UTC by gavinhoward

This comes from [this HN thread][1].

Since `rep` always opens a pager (except for one page?), it interferes with the editor opening at the same time.

So I added `--stdout` to force `rep` to output to `stdout`.

This PR may not be great. I am not a Rust programmer, and I admit that I did it in the dumbest way possible.

I'm open to harsh criticism here since this is my first public contribution using Rust. This includes criticism about how I implemented this.

I also tried running `rustfmt`, but it screamed about being deprecated. I tried installing `rustfmt-nightly`, and it failed. So if style is wrong, I'm sorry, and I'll fix it manually.

[1]: https://news.ycombinator.com/item?id=38816306

2023-12-30 18:35 UTC, gavinhoward commented
Oh, and I understand if this is not something you want. :)

2023-12-31 10:45 UTC, robenkleene requested changes

2023-12-31 10:45 UTC, robenkleene commented on src/input.rs
> +            else {
This should be on one line, e.g., `} else {`

2023-12-31 10:45 UTC, robenkleene commented on src/cli.rs
> +    /// Enable printing to stdout
What do you think about "/// Force printing to standard output without using a pager"?

2023-12-31 10:48 UTC, robenkleene commented
Thanks @gavinhoward we definitely want to support the use case from the Hacker News comment! I added a couple of minor comments to PR, address those and we'll merge this.

2023-12-31 15:57 UTC, gavinhoward commented on src/cli.rs
> +    /// Enable printing to stdout
I like that much better.

2024-01-01 10:22 UTC, robenkleene approved these changes

2024-01-01 10:22 UTC, merged